### ISSUE TITLE
Link to twisting squares colab is broken

### ISSUE THREAD

**Issue by jbrownkramer** [RyannDaGreat/Diffusion-Illusions#10]
In the readme.md, the link should be https://githubtocolab.com/RyannDaGreat/Diffusion-Illusions/blob/master/twisting_squares_colab.ipynb, but it is https://githubtocolab.com/RyannDaGreat/Diffusion-Illusions/blob/master/twisting_squares.ipynb

**Comment by RyannDaGreat** [comment]
Fixed! Thank you for pointing this out
