### ISSUE TITLE
Download link for Folding Tile Illusions

### ISSUE THREAD

**Issue by jefemagril** [RyannDaGreat/Diffusion-Illusions#7]
Amazing work, I love it! I was wondering since you provided downloads for many of the examples on the website if you wouldn't mind also providing the Folding Tile Illusions for download also.

**Comment by RyannDaGreat** [comment]
I will be releasing a colab later today to generate the tile illusions! As for image downloads, you can find them in this repo - but I'll include a PDF as well for easy printing

**Comment by jefemagril** [comment]
Thanks! Sorry but I've looked through this repo and I don't see any images.

**Comment by RyannDaGreat** [comment]
Hi! Please check the website - I've created a PDF with a bunch of them! Here's a direct link: https://diffusionillusions.com/assets/grid_images.pdf 
I've included thin lines to indicate where you should cut the paper once printed!
Also the website has been updated with a new Colab link for folding tiles and for parker puzzles :)
